Rspec編04　Fix testcode
kuboyuya/rspec_app_exam pull request #1
Opened 2021-01-09 05:16 UTC by kuboyuya

>こちら、解答例のNG版です。
>何が問題か、どう修正すべきかを考えてみてください。
>https://github.com/runtequn/rspec_app_exam/pull/1
>上記のPRを参考に修正ができたら、ご自身のtimesから講師の伊藤宛に、GitHubのPRのURLを連絡してレビューを依頼し
>てください。

ここまでの課題を終えました。

概要
・TODOのリファクタリング
　　let traitを使用

・FIXMEの修正
　1.新たなタブを開いている挙動に気づくのに時間がかかりました。
　
　2.ヘルパーメソッドを使用すれば、実装側とテスト側のフォーマットを同じにできることには気付きませんでした。
　
　3.ファクトリのtitleをsecuenceでユニークにしましたがこれで合っているか、、、

>Factoryの定義を変更してテスト失敗を防いでいますが、テストケースとFactoryの設定値に依存性が生じています。
>テスト対象の画面をブラウザの検証ツールで開いて、どう修正するべきかを考えてみてください。
>it 'Taskを編集した場合、一覧画面で編集後の内容が表示されること' のテストケースにヒントがあります

[![Image from Gyazo](https://i.gyazo.com/7babf0272c81608a3a4959bd3a3528b8.png)](https://gyazo.com/7babf0272c81608a3a4959bd3a3528b8)

確認よろしくお願いします。

2021-01-12 03:52 UTC, yuji91 requested changes
コメントしました。各指摘事項に対応するコミットIDを返答頂けると確認しやすいです。

2021-01-12 03:52 UTC, yuji91 commented on spec/system/task_spec.rb
> +    include ApplicationHelper
`rails_helper.rb`に記載した方が、他のSpecファイルでもHelperのメソッドを使えるようになるので良いかもしれません。

2021-01-12 03:52 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).not_to have_content delete_task.title
Taskのテストデータのタイトルにテストケースが依存しているので、テストデータはそのままでどう修正すれば良いかを考えて見て欲しいです。

2021-01-12 03:52 UTC, yuji91 commented on spec/factories/tasks.rb
> +    sequence(:title) { |n| "Task#{n}" }
課題の都合上、この部分は変更を戻して頂きたいです（タイトルの定義が変わるとテストケースが失敗するようなケースを防ぎたいため、タイトルに関わらずテストが通るようにしたいです。）

2021-01-12 12:40 UTC, kuboyuya commented on spec/system/task_spec.rb
> +        expect(page).not_to have_content delete_task.title
a9e7120で修正しました。

2021-01-12 12:42 UTC, kuboyuya commented on spec/factories/tasks.rb
> +    sequence(:title) { |n| "Task#{n}" }
[11760f4](url)

2021-01-12 12:43 UTC, kuboyuya commented on spec/system/task_spec.rb
> +    include ApplicationHelper
[a9e7120](https://github.com/kuboyuya/rspec_app_exam/pull/1/commits/a9e7120f5ed1bee86bbd7c37d442de2d260fa2a5)で修正しました。

2021-01-15 04:33 UTC, yuji91 requested changes
コメントしました！

2021-01-15 04:33 UTC, yuji91 commented on spec/factories/tasks.rb
> +      association :project
trait内でassociation :projectを定義していますが、task全体に定義しましょう。
※このtrait以外のtaskを作成したいときもprojectとの関連を作成できるため。

2021-01-15 04:33 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task) { create(:task, project_id: project.id )}
associationの定義により、project_idの指定は省略できます。
```suggestion
  let(:task) { create(:task)}
```

2021-01-15 04:33 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).to have_content 'Task'
Taskという文字が画面にあるだけでテストが通ってしまうので、変更前の形が良いと思います。

2021-01-15 04:33 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(short_time(Task.last.deadline))
`last`など最後に出来たデータを前提とした記載は避けた方が良いです。
```suggestion
        expect(find('.task_list')).to have_content(short_time(Time.current))
```

2021-01-16 00:54 UTC, kuboyuya commented on spec/system/task_spec.rb
> +        # expect(find('.task_list')).to have_content(Task.last.deadline.strftime('%-m/%d %-H:%M'))
667f43f コメントを削除しました。

2021-01-16 00:55 UTC, kuboyuya commented on spec/system/task_spec.rb
> +        task = create(:task, :task_done_yesterday)
ec327c9　trait名をdoneに変更しました。

2021-01-16 00:56 UTC, kuboyuya commented on spec/system/task_spec.rb
> +        delete_task = task
9b5c1e4　余計なローカル変数を削除しました。

2021-01-16 01:00 UTC, kuboyuya commented on spec/factories/tasks.rb
> +      association :project
7f6f618 task全体の定義に変更しました。

2021-01-16 01:00 UTC, kuboyuya commented on spec/system/task_spec.rb
> +  let(:task) { create(:task, project_id: project.id )}
7f6f618 task全体の定義に変更しました。

2021-01-16 01:05 UTC, kuboyuya commented on spec/system/task_spec.rb
> +        expect(page).to have_content 'Task'
8ff7ae1 元に戻しました。

2021-01-16 01:06 UTC, kuboyuya commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(short_time(Task.last.deadline))
cd93611　最後にできたデータではなく、現在の時刻でtestするようにへんこうしました。

2021-01-16 03:51 UTC, yuji91 requested changes
レビュー依頼の前にコード差分全体を問題ないか自己確認できると良いと思います！
https://github.com/kuboyuya/rspec_app_exam/pull/1/files

2021-01-16 03:51 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task
`expect(page).to have_content task.title`の`task.title`実行時にtaskのletが呼び出されるため、11行目で宣言する必要はないかと思いました。確認してみてください。

2021-01-16 03:51 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task) { create(:task )}
細かいですが、記法は合わせましょう。
```suggestion
  let(:task) { create(:task) }
```

2021-01-16 03:51 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task
`let!`を使うと`task`と宣言しなくて済みますね。

2021-01-16 05:05 UTC, kuboyuya commented on spec/system/task_spec.rb
> +        task
1fcba56 不要な宣言を削除しました。

2021-01-16 05:06 UTC, kuboyuya commented on spec/system/task_spec.rb
> +  let(:task) { create(:task )}
abed343　記法を統一しました。

2021-01-16 05:06 UTC, kuboyuya commented on spec/system/task_spec.rb
> +        task
f14bd16　let!を用いてtaskと宣言せずにすむようにしました。

2021-01-16 05:26 UTC, kuboyuya commented
> レビュー依頼の前にコード差分全体を問題ないか自己確認できると良いと思います！

お手数おかけしてすいません💦

2021-01-16 05:48 UTC, kuboyuya commented on spec/system/task_spec.rb
> +        task
7c707a0 不要な宣言を削除しました。

2021-01-16 05:50 UTC, kuboyuya commented on spec/system/task_spec.rb
> +        task
54e0068 let!を用いて、不要な宣言を削除しました。

2021-01-16 06:55 UTC, yuji91 requested changes
ソースコードに変更を加えたので、テスト結果が改めて問題ないかどうかキャプチャも送って頂けるとありがたいです！

2021-01-16 06:55 UTC, yuji91 commented on spec/factories/tasks.rb
> +
ここは改行しなくても良いかと思いました。

2021-01-16 08:12 UTC, kuboyuya commented on spec/factories/tasks.rb
> +
9fe1ee4 改行を削除しました。

2021-01-16 08:15 UTC, kuboyuya commented
テスト結果キャプチャ

[![Image from Gyazo](https://i.gyazo.com/8b4af383f4b9829f3cd6b23b49daa823.png)](https://gyazo.com/8b4af383f4b9829f3cd6b23b49daa823)

2021-01-16 09:27 UTC, yuji91 approved these changes

2021-01-16 09:28 UTC, merged